apiVersion: v1
kind: Pod
metadata:
  name: netscaler-exporter
  namespace: kube-system
  labels:
    app: netscaler-exporter
spec:
  containers:
    - name: netscaler-exporter
      image: ghcr.io/thg-ice/netscaler-exporter:v0.0.4 
      args:
        - "--target-nsip=10.10.127.126"
        - "--port=8888"
        - "--metric=lbvserver"
        - "--log-level=DEBUG"
        - "--vlb-prefix-filter=autoice.{5}-(prod|nonprod)"
      imagePullPolicy: Always
      volumeMounts:
      - name: nslogin
        mountPath: "/mnt/nslogin"
        readOnly: true
      securityContext:
        readOnlyRootFilesystem: true
  volumes:
  - name: nslogin
    secret:
      secretName: nslogin
---
apiVersion: v1
kind: Service
metadata:
  name: netscaler-exporter
  namespace: kube-system
  labels:
    app: netscaler-exporter
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    name: exporter-port
  selector:
    app: netscaler-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netscaler-exporter
  namespace: kube-system
  labels:
    app: netscaler-exporter
spec:
  selector:
    matchLabels:
      app: netscaler-exporter
  endpoints:
  - port: exporter-port
